nginx:
  restart: always
  image: "nginx:alpine"
  ports:
    - 443:443
  links:
    - registry:registry
  volumes:
    - ./auth:/etc/nginx/conf.d
    - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro

registry:
  restart: always
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - ../data:/var/lib/registry
    - ./config.yml:/etc/docker/registry/config.yml
