nginx2:
  restart: always
  image: "nginx:alpine"
  ports:
    - 442:443
  links:
    - registry2:registry
  volumes:
    - ./auth:/etc/nginx/conf.d
    - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro

registry2:
  restart: always
  image: registry:2
  ports:
    - 127.0.0.1:5002:5000
  volumes:
    - ../data:/var/lib/registry
